# Generated by Django 3.2.9 on 2021-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
