# Generated by Django 3.2.9 on 2021-11-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altexerciselist',
            name='alt_id_list',
        ),
    ]
