# Generated by Django 3.2.9 on 2021-11-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_altexerciselist_alt_id_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='altexerciselist',
            name='alt_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
