# Generated by Django 3.2.9 on 2021-11-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercise_exercise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_id',
        ),
    ]
