# Generated by Django 3.2.9 on 2021-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_exercise_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
