# Generated by Django 3.2.9 on 2021-12-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_program_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
