# Generated by Django 3.2.9 on 2022-01-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workout_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
