# Generated by Django 3.2.9 on 2022-01-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_program_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.URLField(default='https://www.google.co.in/'),
            preserve_default=False,
        ),
    ]
