# Generated by Django 3.2.9 on 2022-01-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
