# Generated by Django 3.2.9 on 2022-02-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
