# Generated by Django 3.2.9 on 2022-01-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_trainer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='wallet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
