# Generated by Django 3.2.9 on 2022-01-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_trainer_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.URLField(default='https://www.google.co.in/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.URLField(default='https://www.google.co.in/'),
            preserve_default=False,
        ),
    ]
